---
deployment:
  tasks:
    - export SRC=$(pwd)
    - export PUBLIC=/home/simplees/public_html
    - export SUB=$PUBLIC/simplee.sub-yorkhost.fr
    - /bin/mkdir -p $SUB/api/data
    - shopt -s dotglob
    - /bin/cp -af $SRC/* $SUB/
    - /bin/chmod -R 755 $SUB
    - /bin/chmod 777 $SUB/api/data
